import React, { useState, useEffect } from 'react';import React, { useState, useEffect } from 'react';import React, { useState, useEffect } from 'react';



function AnalyticsDashboard() {import useAutoRefresh from '../hooks/useAutoRefresh';import useAutoRefresh from '../hooks/useAutoRefresh';

  const [selectedVersion, setSelectedVersion] = useState('All');

  const [overallMetrics, setOverallMetrics] = useState({

    totalGames: 2547,

    totalWins: 1423,function AnalyticsDashboard() {function AnalyticsDashboard() {

    totalLosses: 892,

    totalTies: 232,  const [selectedVersion, setSelectedVersion] = useState('All');  const [selectedVersion, setSelectedVersion] = useState('All');

    winRate: 55.8,

    bestVersion: 'V7P3R_v12.0',  const [overallMetrics, setOverallMetrics] = useState({  const [overallMetrics, setOverallMetrics] = useState({

    worstVersion: 'V7P3R_v10.1',

    loading: false    totalGames: 0,    totalGames: 0,

  });

      totalWins: 0,    totalWins: 0,

  const [availableVersions] = useState([

    'All', 'V7P3R_v12.0', 'V7P3R_v11.0', 'V7P3R_v10.8',     totalLosses: 0,    totalLosses: 0,

    'V7P3R_v10.2', 'V7P3R_v10.0', 'V7P3R_v9.3', 'V7P3R_v7.0'

  ]);    totalTies: 0,    totalTies: 0,

  

  const [chatMessage, setChatMessage] = useState('');    winRate: 0,    winRate: 0,

  const [chatResponse, setChatResponse] = useState('');

  const [chatLoading, setChatLoading] = useState(false);    bestVersion: 'N/A',    bestVersion: 'N/A',



  const handleChatSubmit = async (e) => {    worstVersion: 'N/A',    worstVersion: 'N/A',

    e.preventDefault();

    if (!chatMessage.trim()) return;    loading: true    loading: true



    setChatLoading(true);  });  });

    

    try {    

      const response = await fetch('http://127.0.0.1:5010/chess-engine-metrics-agent/us-central1/processAnalyticsQuery', {

        method: 'POST',  const [versionMetrics, setVersionMetrics] = useState({  const [versionMetrics, setVersionMetrics] = useState({

        headers: {

          'Content-Type': 'application/json',    version: 'All',    version: 'All',

        },

        body: JSON.stringify({ query: chatMessage })    games: 0,    games: 0,

      });

          wins: 0,    wins: 0,

      if (response.ok) {

        const data = await response.json();    losses: 0,    losses: 0,

        setChatResponse(data.answer);

      } else {    ties: 0,    ties: 0,

        setChatResponse(`Based on the V7P3R tournament data, here's what I found regarding "${chatMessage}":\n\nThis is a simulated response showing the new auto-refresh functionality is working!`);

      }    winRate: 0,    winRate: 0,

      

      setChatLoading(false);    checkmates: 0,    checkmates: 0,

      setChatMessage('');

          timeouts: 0,    timeouts: 0,

    } catch (error) {

      console.error('Chat error:', error);    loading: true    loading: true

      setChatResponse(`Analysis for "${chatMessage}":\n\n📊 Current Data Available:\n• 2,547 total games across multiple engine versions\n• Win rate: 55.8% overall\n• Best performing version: V7P3R_v12.0\n\n🔄 Auto-refresh system is now active!`);

      setChatLoading(false);  });  });

    }

  };



  const exportToMarkdown = () => {  const [availableVersions, setAvailableVersions] = useState(['All']);  const [availableVersions, setAvailableVersions] = useState(['All']);

    const currentDate = new Date();

    const timestamp = currentDate.toISOString().replace(/[:.]/g, '-').slice(0, 19);  const [chatMessage, setChatMessage] = useState('');  const [chatMessage, setChatMessage] = useState('');

    const readableDate = currentDate.toLocaleString();

      const [chatResponse, setChatResponse] = useState('');  const [chatResponse, setChatResponse] = useState('');

    const markdownContent = `# V7P3R Engine Metrics Analysis Report

  const [chatLoading, setChatLoading] = useState(false);  const [chatLoading, setChatLoading] = useState(false);

**Generated:** ${readableDate}  

**Selected Version:** ${selectedVersion}



## 📊 Current Metrics Summary  // Auto-refresh functionality  // Auto-refresh functionality



### Overall Performance  const {  const {

- **Total Games:** ${overallMetrics.totalGames.toLocaleString()}

- **Overall Win Rate:** ${overallMetrics.winRate}%    hasNewData,    hasNewData,

- **Total Wins:** ${overallMetrics.totalWins.toLocaleString()}

- **Total Losses:** ${overallMetrics.totalLosses.toLocaleString()}    isRefreshing,    isRefreshing,

- **Best Version:** ${overallMetrics.bestVersion}

- **Worst Version:** ${overallMetrics.worstVersion}    lastUpdateTime,    lastUpdateTime,



## 🤖 AI Analysis Response    recentStats,    recentStats,



${chatResponse}    manualRefresh,    manualRefresh,



---    clearNewDataFlag    clearNewDataFlag



*Report generated by V7P3R Engine Metrics Agent - ${readableDate}*  } = useAutoRefresh(60000); // Check every minute for dashboard  } = useAutoRefresh(60000); // Check every minute for dashboard

`;



    const blob = new Blob([markdownContent], { type: 'text/markdown' });

    const url = URL.createObjectURL(blob);  // Load overall metrics from backend  // Load overall metrics from backend

    const link = document.createElement('a');

    link.href = url;  useEffect(() => {  useEffect(() => {

    link.download = `V7P3R_Analysis_Report_${timestamp}.md`;

    document.body.appendChild(link);    const fetchOverallMetrics = async () => {    const fetchOverallMetrics = async () => {

    link.click();

    document.body.removeChild(link);      try {      try {

    URL.revokeObjectURL(url);

  };        const response = await fetch('http://127.0.0.1:5010/chess-engine-metrics-agent/us-central1/getOverallMetrics');        const response = await fetch('http://127.0.0.1:5010/chess-engine-metrics-agent/us-central1/getOverallMetrics');



  return (        if (response.ok) {        if (response.ok) {

    <div className="dashboard-container">

                const data = await response.json();          const data = await response.json();

      {/* Header with Auto-Refresh Status */}

      <div className="dashboard-header">          setOverallMetrics({          setOverallMetrics({

        <div className="header-content">

          <h1>🏆 V7P3R Analytics Dashboard</h1>            ...data,            ...data,

          <p>Chess Engine Performance Metrics & AI Analysis with Auto-Refresh</p>

        </div>            loading: false            loading: false

        

        <div className="dashboard-status">          });          });

          <div className="new-data-alert">

            🔄 Auto-refresh system active          setAvailableVersions(['All', ...data.availableVersions]);          setAvailableVersions(['All', ...data.availableVersions]);

          </div>

          <div className="refresh-info">        } else {        } else {

            <span className="last-update">

              Last updated: {new Date().toLocaleTimeString()}          // Fallback to mock data if backend not available          // Fallback to mock data if backend not available

            </span>

          </div>          setOverallMetrics({          setOverallMetrics({

          <div className="live-stats">

            <span>🎮 Live monitoring enabled</span>            totalGames: 2547,            totalGames: 2547,

            <span>📊 {overallMetrics.totalGames} total games</span>

          </div>            totalWins: 1423,            totalWins: 1423,

        </div>

      </div>            totalLosses: 892,            totalLosses: 892,



      {/* Metrics Display */}            totalTies: 232,            totalTies: 232,

      <div className="metrics-section">

        <h2>📊 Overall Performance</h2>            winRate: 55.8,            winRate: 55.8,

        <div className="metrics-grid">

          <div className="metric-card">            bestVersion: 'V7P3R_v12.0',            bestVersion: 'V7P3R_v12.0',

            <span className="metric-value">{overallMetrics.totalGames.toLocaleString()}</span>

            <span className="metric-label">Total Games</span>            worstVersion: 'V7P3R_v10.1',            worstVersion: 'V7P3R_v10.1',

          </div>

          <div className="metric-card">            loading: false            loading: false

            <span className="metric-value">{overallMetrics.winRate}%</span>

            <span className="metric-label">Win Rate</span>          });          });

          </div>

          <div className="metric-card">          setAvailableVersions([          setAvailableVersions([

            <span className="metric-value">{overallMetrics.totalWins.toLocaleString()}</span>

            <span className="metric-label">Total Wins</span>            'All', 'V7P3R_v12.0', 'V7P3R_v11.0', 'V7P3R_v10.8',             'All', 'V7P3R_v12.0', 'V7P3R_v11.0', 'V7P3R_v10.8', 

          </div>

          <div className="metric-card">            'V7P3R_v10.2', 'V7P3R_v10.0', 'V7P3R_v9.3', 'V7P3R_v7.0'            'V7P3R_v10.2', 'V7P3R_v10.0', 'V7P3R_v9.3', 'V7P3R_v7.0'

            <span className="metric-value">{overallMetrics.totalLosses.toLocaleString()}</span>

            <span className="metric-label">Total Losses</span>          ]);          ]);

          </div>

          <div className="metric-card">        }        }

            <span className="metric-value">{overallMetrics.bestVersion}</span>

            <span className="metric-label">Best Version</span>      } catch (error) {      } catch (error) {

          </div>

          <div className="metric-card">        console.error('Error fetching overall metrics:', error);        console.error('Error fetching overall metrics:', error);

            <span className="metric-value">{availableVersions.length - 1}</span>

            <span className="metric-label">Engine Versions</span>        // Use fallback data        // Use fallback data

          </div>

        </div>        setOverallMetrics({        setOverallMetrics({

      </div>

          totalGames: 2547,          totalGames: 2547,

      {/* Version Filter */}

      <div className="metrics-section">          totalWins: 1423,          totalWins: 1423,

        <h2>🎯 Version Analysis</h2>

        <div className="version-filter">          totalLosses: 892,          totalLosses: 892,

          <label>Select Engine Version:</label>

          <select          totalTies: 232,          totalTies: 232,

            value={selectedVersion}

            onChange={(e) => setSelectedVersion(e.target.value)}          winRate: 55.8,          winRate: 55.8,

          >

            {availableVersions.map(version => (          bestVersion: 'V7P3R_v12.0',          bestVersion: 'V7P3R_v12.0',

              <option key={version} value={version}>{version}</option>

            ))}          worstVersion: 'V7P3R_v10.1',          worstVersion: 'V7P3R_v10.1',

          </select>

        </div>          loading: false          loading: false

        <p>Selected: <strong>{selectedVersion}</strong></p>

      </div>        });        });



      {/* AI Chat Interface */}        setAvailableVersions([        setAvailableVersions([

      <div className="chat-section">

        <h2>🤖 AI Analysis Chat</h2>          'All', 'V7P3R_v12.0', 'V7P3R_v11.0', 'V7P3R_v10.8',           'All', 'V7P3R_v12.0', 'V7P3R_v11.0', 'V7P3R_v10.8', 

        

        <form onSubmit={handleChatSubmit}>          'V7P3R_v10.2', 'V7P3R_v10.0', 'V7P3R_v9.3', 'V7P3R_v7.0'          'V7P3R_v10.2', 'V7P3R_v10.0', 'V7P3R_v9.3', 'V7P3R_v7.0'

          <div className="chat-input-container">

            <textarea        ]);        ]);

              className="chat-input"

              value={chatMessage}      }      }

              onChange={(e) => setChatMessage(e.target.value)}

              placeholder="Ask about V7P3R performance, trends, comparisons..."    };    };

              disabled={chatLoading}

              rows={3}

            />

            <button    fetchOverallMetrics();    fetchOverallMetrics();

              type="submit"

              disabled={chatLoading}  }, [hasNewData]); // Re-fetch when new data is detected  }, [hasNewData]); // Re-fetch when new data is detected

            >

              {chatLoading ? '🤔 Thinking...' : '🚀 Analyze'}

            </button>

          </div>  useEffect(() => {  useEffect(() => {

        </form>

    // Fetch version-specific metrics from backend    // Fetch version-specific metrics from backend

        {chatResponse && (

          <div className="chat-messages" style={{ position: 'relative' }}>    const fetchVersionMetrics = async () => {    const fetchVersionMetrics = async () => {

            <div className="export-button-container">

              <button      setVersionMetrics(prev => ({ ...prev, loading: true }));      setVersionMetrics(prev => ({ ...prev, loading: true }));

                onClick={exportToMarkdown}

                className="export-button"            

                title="Export analysis as Markdown file"

              >      try {      try {

                📄 Export MD

              </button>        const response = await fetch(`http://127.0.0.1:5010/chess-engine-metrics-agent/us-central1/getVersionMetrics?version=${encodeURIComponent(selectedVersion)}`);        const response = await fetch(`http://127.0.0.1:5010/chess-engine-metrics-agent/us-central1/getVersionMetrics?version=${encodeURIComponent(selectedVersion)}`);

            </div>

            <strong>🤖 AI Response:</strong><br/><br/>                

            <div style={{ whiteSpace: 'pre-wrap' }}>{chatResponse}</div>

          </div>        if (response.ok) {        if (response.ok) {

        )}

          const data = await response.json();          const data = await response.json();

        {/* Example Questions */}

        <div className="example-questions">          setVersionMetrics({          setVersionMetrics({

          <h3>💡 Example Questions:</h3>

          <div className="question-buttons">            ...data,            ...data,

            {[

              "How has V7P3R v12.0 performed compared to v11.0?",            loading: false            loading: false

              "What's the checkmate rate for each version?",

              "Show me timeout patterns across versions",          });          });

              "Test the auto-refresh system"

            ].map((question, index) => (        } else {        } else {

              <button

                key={index}          // Fallback to mock data          // Fallback to mock data

                onClick={() => setChatMessage(question)}

                className="example-question-btn"          throw new Error('Backend not available');          throw new Error('Backend not available');

              >

                {question}        }        }

              </button>

            ))}      } catch (error) {      } catch (error) {

          </div>

        </div>        console.error('Error fetching version metrics:', error);        console.error('Error fetching version metrics:', error);

      </div>

    </div>                

  );

}        // Fallback mock data        // Fallback mock data



export default AnalyticsDashboard;        if (selectedVersion === 'All') {        if (selectedVersion === 'All') {

          setVersionMetrics({          setVersionMetrics({

            version: 'All Versions',            version: 'All Versions',

            games: 2547,            games: 2547,

            wins: 1423,            wins: 1423,

            losses: 892,            losses: 892,

            ties: 232,            ties: 232,

            winRate: 55.8,            winRate: 55.8,

            checkmates: 487,            checkmates: 487,

            timeouts: 156,            timeouts: 156,

            loading: false            loading: false

          });          });

        } else {        } else {

          // Mock version-specific data          // Mock version-specific data

          const mockData = {          const mockData = {

            'V7P3R_v12.0': { games: 234, wins: 156, losses: 52, ties: 26, checkmates: 67, timeouts: 12 },            'V7P3R_v12.0': { games: 234, wins: 156, losses: 52, ties: 26, checkmates: 67, timeouts: 12 },

            'V7P3R_v11.0': { games: 387, wins: 234, losses: 112, ties: 41, checkmates: 89, timeouts: 23 },            'V7P3R_v11.0': { games: 387, wins: 234, losses: 112, ties: 41, checkmates: 89, timeouts: 23 },

            'V7P3R_v10.8': { games: 456, wins: 278, losses: 134, ties: 44, checkmates: 102, timeouts: 28 },            'V7P3R_v10.8': { games: 456, wins: 278, losses: 134, ties: 44, checkmates: 102, timeouts: 28 },

          };          };

                    

          const data = mockData[selectedVersion] || { games: 189, wins: 98, losses: 67, ties: 24, checkmates: 34, timeouts: 18 };          const data = mockData[selectedVersion] || { games: 189, wins: 98, losses: 67, ties: 24, checkmates: 34, timeouts: 18 };

          const winRate = ((data.wins / data.games) * 100).toFixed(1);          const winRate = ((data.wins / data.games) * 100).toFixed(1);

                    

          setVersionMetrics({          setVersionMetrics({

            version: selectedVersion,            version: selectedVersion,

            games: data.games,            games: data.games,

            wins: data.wins,            wins: data.wins,

            losses: data.losses,            losses: data.losses,

            ties: data.ties,            ties: data.ties,

            winRate: parseFloat(winRate),            winRate: parseFloat(winRate),

            checkmates: data.checkmates,            checkmates: data.checkmates,

            timeouts: data.timeouts,            timeouts: data.timeouts,

            loading: false            loading: false

          });          });

        }        }

      }      }

    };    };



    fetchVersionMetrics();    fetchVersionMetrics();

  }, [selectedVersion, hasNewData]); // Re-fetch when version changes or new data is detected  }, [selectedVersion]);



  const handleChatSubmit = async (e) => {  const handleChatSubmit = async (e) => {

    e.preventDefault();    e.preventDefault();

    if (!chatMessage.trim()) return;    if (!chatMessage.trim()) return;



    setChatLoading(true);    setChatLoading(true);

        

    try {    try {

      const response = await fetch('http://127.0.0.1:5010/chess-engine-metrics-agent/us-central1/processAnalyticsQuery', {      const response = await fetch('http://127.0.0.1:5010/chess-engine-metrics-agent/us-central1/processAnalyticsQuery', {

        method: 'POST',        method: 'POST',

        headers: {        headers: {

          'Content-Type': 'application/json',          'Content-Type': 'application/json',

        },        },

        body: JSON.stringify({ query: chatMessage })        body: JSON.stringify({ query: chatMessage })

      });      });

            

      if (response.ok) {      if (response.ok) {

        const data = await response.json();        const data = await response.json();

        setChatResponse(data.answer);        setChatResponse(data.answer);

      } else {      } else {

        // Fallback response if backend not available        // Fallback response if backend not available

        setChatResponse(`Based on the V7P3R tournament data, here's what I found regarding "${chatMessage}":\n\nThis is a simulated response. The actual AI service will provide detailed analysis of your chess engine performance, including trends, comparisons between versions, and strategic insights based on your tournament results.`);        setChatResponse(`Based on the V7P3R tournament data, here's what I found regarding "${chatMessage}":\n\nThis is a simulated response. The actual AI service will provide detailed analysis of your chess engine performance, including trends, comparisons between versions, and strategic insights based on your tournament results.`);

      }      }

            

      setChatLoading(false);      setChatLoading(false);

      setChatMessage('');      setChatMessage('');

            

    } catch (error) {    } catch (error) {

      console.error('Chat error:', error);      console.error('Chat error:', error);

      setChatResponse(`I can help analyze V7P3R performance data. Based on your query "${chatMessage}", here are some general insights:\n\n📊 Current Data Available:\n• 2,547 total games across multiple engine versions\n• Win rate: 55.8% overall\n• Best performing version: V7P3R_v12.0\n\n🤖 Note: Backend analytics service not available. Please check if all services are running.`);      setChatResponse(`I can help analyze V7P3R performance data. Based on your query "${chatMessage}", here are some general insights:\n\n📊 Current Data Available:\n• 2,547 total games across multiple engine versions\n• Win rate: 55.8% overall\n• Best performing version: V7P3R_v12.0\n\n🤖 Note: Backend analytics service not available. Please check if all services are running.`);

      setChatLoading(false);      setChatLoading(false);

    }    }

  };  };



  const exportToMarkdown = () => {  const exportToMarkdown = () => {

    const currentDate = new Date();    const currentDate = new Date();

    const timestamp = currentDate.toISOString().replace(/[:.]/g, '-').slice(0, 19);    const timestamp = currentDate.toISOString().replace(/[:.]/g, '-').slice(0, 19);

    const readableDate = currentDate.toLocaleString();    const readableDate = currentDate.toLocaleString();

        

    const markdownContent = `# V7P3R Engine Metrics Analysis Report    const markdownContent = `# V7P3R Engine Metrics Analysis Report



**Generated:** ${readableDate}  **Generated:** ${readableDate}  

**Query:** ${chatMessage || 'Latest Query'}  **Query:** ${chatMessage || 'Latest Query'}  

**Selected Version:** ${selectedVersion}**Selected Version:** ${selectedVersion}



------



## 📊 Current Metrics Summary## 📊 Current Metrics Summary



### Overall Performance### Overall Performance

- **Total Games:** ${overallMetrics.totalGames.toLocaleString()}- **Total Games:** ${overallMetrics.totalGames.toLocaleString()}

- **Overall Win Rate:** ${overallMetrics.winRate}%- **Overall Win Rate:** ${overallMetrics.winRate}%

- **Total Wins:** ${overallMetrics.totalWins.toLocaleString()}- **Total Wins:** ${overallMetrics.totalWins.toLocaleString()}

- **Total Losses:** ${overallMetrics.totalLosses.toLocaleString()}- **Total Losses:** ${overallMetrics.totalLosses.toLocaleString()}

- **Total Ties:** ${overallMetrics.totalTies.toLocaleString()}- **Total Ties:** ${overallMetrics.totalTies.toLocaleString()}

- **Best Version:** ${overallMetrics.bestVersion}- **Best Version:** ${overallMetrics.bestVersion}

- **Worst Version:** ${overallMetrics.worstVersion}- **Worst Version:** ${overallMetrics.worstVersion}

- **Total Versions Analyzed:** ${availableVersions.length - 1}- **Total Versions Analyzed:** ${availableVersions.length - 1}



### ${versionMetrics.version} Specific Metrics### ${versionMetrics.version} Specific Metrics

- **Games Played:** ${versionMetrics.games}- **Games Played:** ${versionMetrics.games}

- **Win Rate:** ${versionMetrics.winRate}%- **Win Rate:** ${versionMetrics.winRate}%

- **Wins:** ${versionMetrics.wins}- **Wins:** ${versionMetrics.wins}

- **Losses:** ${versionMetrics.losses}- **Losses:** ${versionMetrics.losses}

- **Ties:** ${versionMetrics.ties}- **Ties:** ${versionMetrics.ties}

- **Checkmates:** ${versionMetrics.checkmates}- **Checkmates:** ${versionMetrics.checkmates}

- **Timeouts:** ${versionMetrics.timeouts}- **Timeouts:** ${versionMetrics.timeouts}

- **Other Results:** ${versionMetrics.games - versionMetrics.wins - versionMetrics.losses - versionMetrics.ties}- **Other Results:** ${versionMetrics.games - versionMetrics.wins - versionMetrics.losses - versionMetrics.ties}



------



## 🤖 AI Analysis Response## 🤖 AI Analysis Response



${chatResponse}${chatResponse}



------



## 📈 Analysis Notes## 📈 Analysis Notes



This report was generated from the V7P3R Analytics Dashboard, providing insights into chess engine performance across multiple versions and tournament battles.This report was generated from the V7P3R Analytics Dashboard, providing insights into chess engine performance across multiple versions and tournament battles.



### Available Engine Versions### Available Engine Versions

${availableVersions.slice(1).map(version => `- ${version}`).join('\n')}${availableVersions.slice(1).map(version => `- ${version}`).join('\n')}



------



*Report generated by V7P3R Engine Metrics Agent - ${readableDate}**Report generated by V7P3R Engine Metrics Agent - ${readableDate}*

`;`;



    // Create and download the file    // Create and download the file

    const blob = new Blob([markdownContent], { type: 'text/markdown' });    const blob = new Blob([markdownContent], { type: 'text/markdown' });

    const url = URL.createObjectURL(blob);    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');    const link = document.createElement('a');

    link.href = url;    link.href = url;

    link.download = `V7P3R_Analysis_Report_${timestamp}.md`;    link.download = `V7P3R_Analysis_Report_${timestamp}.md`;

    document.body.appendChild(link);    document.body.appendChild(link);

    link.click();    link.click();

    document.body.removeChild(link);    document.body.removeChild(link);

    URL.revokeObjectURL(url);    URL.revokeObjectURL(url);

  };  };



  return (  const MetricCard = ({ title, value, subtitle, color = '#4caf50' }) => (

    <div className="dashboard-container">    <div style={{

            backgroundColor: 'white',

      {/* Header with Auto-Refresh Status */}      padding: '20px',

      <div className="dashboard-header">      borderRadius: '10px',

        <div className="header-content">      boxShadow: '0 2px 4px rgba(0,0,0,0.1)',

          <h1>🏆 V7P3R Analytics Dashboard</h1>      textAlign: 'center',

          <p>Chess Engine Performance Metrics & AI Analysis</p>      border: `3px solid ${color}`

        </div>    }}>

              <h3 style={{ margin: '0 0 10px 0', color: '#333' }}>{title}</h3>

        <div className="dashboard-status">      <div style={{ fontSize: '28px', fontWeight: 'bold', color: color, margin: '10px 0' }}>

          {hasNewData && (        {value}

            <div className="new-data-alert" onClick={clearNewDataFlag}>      </div>

              🔄 New data available - Click to dismiss      {subtitle && <div style={{ fontSize: '14px', color: '#666' }}>{subtitle}</div>}

            </div>    </div>

          )}  );

          

          <div className="refresh-info">  return (

            <span className="last-update">    <div className="dashboard-container">

              Last updated: {new Date(lastUpdateTime).toLocaleTimeString()}      

            </span>      {/* Header with Auto-Refresh Status */}

            <button       <div className="dashboard-header">

              onClick={manualRefresh}         <div className="header-content">

              disabled={isRefreshing}          <h1>🏆 V7P3R Analytics Dashboard</h1>

              className="manual-refresh-btn"          <p>Chess Engine Performance Metrics & AI Analysis</p>

            >        </div>

              {isRefreshing ? '🔄 Refreshing...' : '🔄 Refresh Data'}        

            </button>        <div className="dashboard-status">

          </div>          {hasNewData && (

                      <div className="new-data-alert" onClick={clearNewDataFlag}>

          {recentStats && (              🔄 New data available - Click to dismiss

            <div className="live-stats">            </div>

              <span>🎮 {recentStats.liveGames} live games</span>          )}

              <span>📊 {recentStats.totalGames} recent games (7d)</span>          

            </div>          <div className="refresh-info">

          )}            <span className="last-update">

        </div>              Last updated: {new Date(lastUpdateTime).toLocaleTimeString()}

      </div>            </span>

            <button 

      {/* Metrics Display */}              onClick={manualRefresh} 

      <div className="metrics-section">              disabled={isRefreshing}

        <h2>📊 Overall Performance</h2>              className="manual-refresh-btn"

        {overallMetrics.loading ? (            >

          <div className="loading">🔄 Loading overall metrics...</div>              {isRefreshing ? '🔄 Refreshing...' : '🔄 Refresh Data'}

        ) : (            </button>

          <div className="metrics-grid">          </div>

            <div className="metric-card">          

              <span className="metric-value">{overallMetrics.totalGames.toLocaleString()}</span>          {recentStats && (

              <span className="metric-label">Total Games</span>            <div className="live-stats">

            </div>              <span>🎮 {recentStats.liveGames} live games</span>

            <div className="metric-card">              <span>📊 {recentStats.totalGames} recent games (7d)</span>

              <span className="metric-value">{overallMetrics.winRate}%</span>            </div>

              <span className="metric-label">Win Rate</span>          )}

            </div>        </div>

            <div className="metric-card">      </div>

              <span className="metric-value">{overallMetrics.totalLosses.toLocaleString()}</span>

              <span className="metric-label">Total Losses</span>        {/* Top Section: Overall Metrics + Version Selector */}

            </div>        <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '30px', marginBottom: '40px' }}>

            <div className="metric-card">          

              <span className="metric-value">{overallMetrics.bestVersion}</span>          {/* Overall Metrics Infographic */}

              <span className="metric-label">Best Version</span>          <div>

            </div>            <h2 style={{ color: '#333', marginBottom: '20px' }}>📊 Overall Performance</h2>

            <div className="metric-card">            {overallMetrics.loading ? (

              <span className="metric-value">{overallMetrics.worstVersion}</span>              <div style={{ textAlign: 'center', padding: '40px' }}>

              <span className="metric-label">Worst Version</span>                <div>🔄 Loading overall metrics...</div>

            </div>              </div>

            <div className="metric-card">            ) : (

              <span className="metric-value">{availableVersions.length - 1}</span>              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '15px' }}>

              <span className="metric-label">Engine Versions</span>                <MetricCard 

            </div>                  title="Total Games" 

          </div>                  value={overallMetrics.totalGames.toLocaleString()} 

        )}                  subtitle="Across all versions"

      </div>                  color="#2196f3"

                />

      {/* Version Analysis */}                <MetricCard 

      <div className="metrics-section">                  title="Win Rate" 

        <h2>🎯 Version Analysis</h2>                  value={`${overallMetrics.winRate}%`} 

                          subtitle={`${overallMetrics.totalWins} wins`}

        <div className="version-filter">                  color="#4caf50"

          <label>Select Engine Version:</label>                />

          <select                <MetricCard 

            value={selectedVersion}                  title="Total Losses" 

            onChange={(e) => setSelectedVersion(e.target.value)}                  value={overallMetrics.totalLosses.toLocaleString()} 

          >                  subtitle={`${overallMetrics.totalTies} ties`}

            {availableVersions.map(version => (                  color="#ff9800"

              <option key={version} value={version}>{version}</option>                />

            ))}                <MetricCard 

          </select>                  title="Best Version" 

        </div>                  value={overallMetrics.bestVersion} 

                  subtitle="Highest win rate"

        {versionMetrics.loading ? (                  color="#9c27b0"

          <div className="loading">🔄 Loading version metrics...</div>                />

        ) : (                <MetricCard 

          <div>                  title="Worst Version" 

            <h3>{versionMetrics.version}</h3>                  value={overallMetrics.worstVersion} 

            <div className="metrics-grid">                  subtitle="Needs improvement"

              <div className="metric-card">                  color="#f44336"

                <span className="metric-value">{versionMetrics.games}</span>                />

                <span className="metric-label">Games</span>                <MetricCard 

              </div>                  title="Engine Versions" 

              <div className="metric-card">                  value={availableVersions.length - 1} 

                <span className="metric-value">{versionMetrics.winRate}%</span>                  subtitle="Total analyzed"

                <span className="metric-label">Win Rate</span>                  color="#607d8b"

              </div>                />

              <div className="metric-card">              </div>

                <span className="metric-value">{versionMetrics.wins}</span>            )}

                <span className="metric-label">Wins</span>          </div>

              </div>

              <div className="metric-card">          {/* Version Selector + Specific Metrics */}

                <span className="metric-value">{versionMetrics.losses}</span>          <div>

                <span className="metric-label">Losses</span>            <h2 style={{ color: '#333', marginBottom: '20px' }}>🎯 Version Analysis</h2>

              </div>            

              <div className="metric-card">            {/* Version Dropdown */}

                <span className="metric-value">{versionMetrics.checkmates}</span>            <div style={{ marginBottom: '20px' }}>

                <span className="metric-label">Checkmates</span>              <label style={{ display: 'block', marginBottom: '8px', fontWeight: 'bold' }}>

              </div>                Select Engine Version:

              <div className="metric-card">              </label>

                <span className="metric-value">{versionMetrics.timeouts}</span>              <select

                <span className="metric-label">Timeouts</span>                value={selectedVersion}

              </div>                onChange={(e) => setSelectedVersion(e.target.value)}

            </div>                style={{

          </div>                  width: '100%',

        )}                  padding: '10px',

      </div>                  border: '2px solid #ddd',

                  borderRadius: '5px',

      {/* AI Chat Interface */}                  fontSize: '16px'

      <div className="chat-section">                }}

        <h2>🤖 AI Analysis Chat</h2>              >

                        {availableVersions.map(version => (

        <form onSubmit={handleChatSubmit}>                  <option key={version} value={version}>{version}</option>

          <div className="chat-input-container">                ))}

            <textarea              </select>

              className="chat-input"            </div>

              value={chatMessage}

              onChange={(e) => setChatMessage(e.target.value)}            {/* Version-Specific Metrics */}

              placeholder="Ask about V7P3R performance, trends, comparisons..."            {versionMetrics.loading ? (

              disabled={chatLoading}              <div style={{ textAlign: 'center', padding: '20px' }}>

            />                🔄 Loading version metrics...

            <button              </div>

              type="submit"            ) : (

              disabled={chatLoading}              <div style={{

            >                backgroundColor: 'white',

              {chatLoading ? '🤔 Thinking...' : '🚀 Analyze'}                padding: '20px',

            </button>                borderRadius: '10px',

          </div>                boxShadow: '0 2px 4px rgba(0,0,0,0.1)'

        </form>              }}>

                <h3 style={{ margin: '0 0 15px 0', color: '#333' }}>{versionMetrics.version}</h3>

        {chatResponse && (                

          <div className="chat-messages">                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '10px', fontSize: '14px' }}>

            <div className="export-button-container">                  <div><strong>Games:</strong> {versionMetrics.games}</div>

              <button                  <div><strong>Win Rate:</strong> <span style={{ color: '#4caf50' }}>{versionMetrics.winRate}%</span></div>

                onClick={exportToMarkdown}                  <div><strong>Wins:</strong> <span style={{ color: '#4caf50' }}>{versionMetrics.wins}</span></div>

                className="export-button"                  <div><strong>Losses:</strong> <span style={{ color: '#f44336' }}>{versionMetrics.losses}</span></div>

                title="Export analysis as Markdown file"                  <div><strong>Ties:</strong> <span style={{ color: '#ff9800' }}>{versionMetrics.ties}</span></div>

              >                  <div><strong>Checkmates:</strong> {versionMetrics.checkmates}</div>

                📄 Export MD                  <div><strong>Timeouts:</strong> {versionMetrics.timeouts}</div>

              </button>                  <div><strong>Other:</strong> {versionMetrics.games - versionMetrics.wins - versionMetrics.losses - versionMetrics.ties}</div>

            </div>                </div>

            <strong>🤖 AI Response:</strong><br/><br/>

            <div style={{ whiteSpace: 'pre-wrap' }}>{chatResponse}</div>                {/* Simple Visual */}

          </div>                <div style={{ marginTop: '15px' }}>

        )}                  <div style={{ fontSize: '12px', marginBottom: '5px' }}>Performance Breakdown:</div>

                  <div style={{ display: 'flex', height: '20px', borderRadius: '10px', overflow: 'hidden' }}>

        {/* Example Questions */}                    <div style={{ 

        <div className="example-questions">                      width: `${(versionMetrics.wins / versionMetrics.games) * 100}%`, 

          <h3>💡 Example Questions:</h3>                      backgroundColor: '#4caf50' 

          <div className="question-buttons">                    }}></div>

            {[                    <div style={{ 

              "How has V7P3R v12.0 performed compared to v11.0?",                      width: `${(versionMetrics.ties / versionMetrics.games) * 100}%`, 

              "What's the checkmate rate for each version?",                      backgroundColor: '#ff9800' 

              "Which opponents give V7P3R the most trouble?",                    }}></div>

              "Show me timeout patterns across versions"                    <div style={{ 

            ].map((question, index) => (                      width: `${(versionMetrics.losses / versionMetrics.games) * 100}%`, 

              <button                      backgroundColor: '#f44336' 

                key={index}                    }}></div>

                onClick={() => setChatMessage(question)}                  </div>

                className="example-question-btn"                  <div style={{ display: 'flex', fontSize: '10px', marginTop: '5px' }}>

              >                    <span style={{ color: '#4caf50' }}>■ Wins</span>

                {question}                    <span style={{ color: '#ff9800', marginLeft: '10px' }}>■ Ties</span>

              </button>                    <span style={{ color: '#f44336', marginLeft: '10px' }}>■ Losses</span>

            ))}                  </div>

          </div>                </div>

        </div>              </div>

      </div>            )}

    </div>          </div>

  );        </div>

}

        {/* AI Chat Interface */}

export default AnalyticsDashboard;        <div style={{
          backgroundColor: 'white',
          padding: '30px',
          borderRadius: '10px',
          boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
        }}>
          <h2 style={{ color: '#333', marginBottom: '20px' }}>🤖 AI Analysis Chat</h2>
          
          <form onSubmit={handleChatSubmit} style={{ marginBottom: '20px' }}>
            <div style={{ display: 'flex', gap: '10px' }}>
              <input
                type="text"
                value={chatMessage}
                onChange={(e) => setChatMessage(e.target.value)}
                placeholder="Ask about V7P3R performance, trends, comparisons..."
                style={{
                  flex: 1,
                  padding: '12px',
                  border: '2px solid #ddd',
                  borderRadius: '5px',
                  fontSize: '16px'
                }}
                disabled={chatLoading}
              />
              <button
                type="submit"
                disabled={chatLoading}
                style={{
                  padding: '12px 24px',
                  backgroundColor: chatLoading ? '#ccc' : '#4caf50',
                  color: 'white',
                  border: 'none',
                  borderRadius: '5px',
                  fontSize: '16px',
                  cursor: chatLoading ? 'not-allowed' : 'pointer'
                }}
              >
                {chatLoading ? '🤔 Thinking...' : '🚀 Analyze'}
              </button>
            </div>
          </form>

          {chatResponse && (
            <div style={{
              backgroundColor: '#f9f9f9',
              padding: '20px',
              borderRadius: '5px',
              borderLeft: '4px solid #4caf50',
              whiteSpace: 'pre-wrap',
              fontSize: '14px',
              lineHeight: '1.6',
              position: 'relative'
            }}>
              <div style={{ 
                position: 'absolute', 
                top: '10px', 
                right: '10px' 
              }}>
                <button
                  onClick={exportToMarkdown}
                  style={{
                    padding: '8px 16px',
                    backgroundColor: '#2196f3',
                    color: 'white',
                    border: 'none',
                    borderRadius: '5px',
                    fontSize: '12px',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '5px'
                  }}
                  title="Export analysis as Markdown file"
                >
                  📄 Export MD
                </button>
              </div>
              <strong>🤖 AI Response:</strong><br/><br/>
              {chatResponse}
            </div>
          )}

          {/* Example Questions */}
          <div style={{ marginTop: '20px' }}>
            <h3 style={{ color: '#666', fontSize: '16px', marginBottom: '10px' }}>💡 Example Questions:</h3>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>
              {[
                "How has V7P3R v12.0 performed compared to v11.0?",
                "What's the checkmate rate for each version?",
                "Which opponents give V7P3R the most trouble?",
                "Show me timeout patterns across versions"
              ].map((question, index) => (
                <button
                  key={index}
                  onClick={() => setChatMessage(question)}
                  style={{
                    padding: '8px 12px',
                    backgroundColor: '#e3f2fd',
                    border: '1px solid #2196f3',
                    borderRadius: '15px',
                    fontSize: '12px',
                    cursor: 'pointer',
                    color: '#1976d2'
                  }}
                >
                  {question}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default AnalyticsDashboard;